version: '3.0'
services:
  json-server:
    image: myimage
    build: .
    command: json-server -H 0.0.0.0 -p 8080 -w /config/db.json
    ports:
      - "8080:8080"
    volumes:
      - ./config:/config
    restart: always
